### ISSUE TITLE
Publishing to Zenodo

### ISSUE THREAD

**Issue by Galadirith** [llondon6/positive#4]
To make this package easily citable I would recommend publishing it on Zenodo. GitHub provide a [guide](https://guides.github.com/activities/citable-code/) for doing this. Among others Zenodo is used by [`gwpy`](https://doi.org/10.5281/zenodo.1304148) and for many SXS projects (https://doi.org/10.5281/zenodo.1233923, https://doi.org/10.5281/zenodo.1215824).

**Comment by llondon6** [comment]
Thanks fo the tip!

**Comment by llondon6** [comment]
@misc{lionel_london_2018_1402516,
  author       = {Lionel London and
                  Edward Fauchon-Jones and
                  EZHamilton},
  title        = {llondon6/positive: charge},
  month        = aug,
  year         = 2018,
  doi          = {10.5281/zenodo.1402516},
  url          = {https://doi.org/10.5281/zenodo.1402516}
}
